[package]
name = "bruthost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.8"
clap = { version = "4.0", features = ["derive"] }
curl = "0.4.44"